
package chefui;
import Networking.Client;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Tarun
 */
public class ChefTable extends javax.swing.JFrame {

    /**
     * Creates new form ChefTable
     */
    Client client = null;
    ArrayList<Object> storeReadyOrder= null;
    
    public ChefTable() {
        initComponents();
        setSize(887, 460);
        storeReadyOrder= new ArrayList<Object>();
        client  = new Client(ChefTable.this);
        client.start();
    }
    public JPanel getPnlDisplayTable(){
        return pnlDisplayTable;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                pnlDisplayTable = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable(){
                        public boolean isCellEditable(int rowIndex, int colIndex) {
                                return false;   //Disallow the editing of any cell
                        }
                };
                btnReady = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                pnlDisplayTable.setLayout(null);

                jTable1.setAutoCreateRowSorter(true);
                jTable1.setBackground(new java.awt.Color(26, 38, 141));
                jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jTable1.setForeground(new java.awt.Color(255, 255, 255));
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null},
                                {null, null, null, null, null},
                                {null, null, null, null, null},
                                {null, null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
                        }
                ));
                jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                jTable1.setGridColor(new java.awt.Color(59, 223, 210));
                jTable1.setRowHeight(30);
                jTable1.setRowMargin(5);
                jTable1.setSurrendersFocusOnKeystroke(true);
                jScrollPane1.setViewportView(jTable1);

                pnlDisplayTable.add(jScrollPane1);
                jScrollPane1.setBounds(0, 0, 940, 360);

                btnReady.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                btnReady.setText("Ready");
                btnReady.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnReadyActionPerformed(evt);
                        }
                });
                pnlDisplayTable.add(btnReady);
                btnReady.setBounds(410, 390, 120, 30);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlDisplayTable, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlDisplayTable, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnReadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadyActionPerformed
        new Thread(()->{
            try {
                 if( jTable1.getSelectedRow() != -1){
                    String getId= jTable1.getModel().getValueAt(jTable1.getSelectedRow(),0).toString();
                    int  check=JOptionPane.showConfirmDialog(null,"Are you sure this order is ready : ", "ChefTable", JOptionPane.INFORMATION_MESSAGE);
                    if(JOptionPane.YES_OPTION == check){
                       ((DefaultTableModel)jTable1.getModel()).removeRow(jTable1.getSelectedRow());
                       client.output.writeObject(getId);
                       client.output.flush();
                    }
                 }
                 else 
                     JOptionPane.showMessageDialog(null,"Please select the order Which is ready : ", "ChefTable", JOptionPane.ERROR_MESSAGE);
             } catch (IOException ex) {
                 JOptionPane.showMessageDialog(null,"Exception in client: " + ex, "ChefTable", JOptionPane.ERROR_MESSAGE);
           }
        }).start(); 
    }//GEN-LAST:event_btnReadyActionPerformed
    public JTable  getPendingOrderTable(){
        return jTable1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChefTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChefTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChefTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChefTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChefTable().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnReady;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JPanel pnlDisplayTable;
        // End of variables declaration//GEN-END:variables
}
