
package UIDesign;
import Database.MySqlConnect;
import java.sql.Connection;
import java.util.Vector;
/**
 *
 * @author Tarun
 */
public class AddOrder extends javax.swing.JPanel {
Connection conn =null;
OrderDetails orderDetails=null;
Dashboard dashboard = null;
    /**
     * Creates new form AddOrder
     */
    public AddOrder(OrderDetails orderDetails,Dashboard dashboard) {
        initComponents();
        this.dashboard=dashboard;
        this.orderDetails = orderDetails;
        MySqlConnect.connectDB();
        this.setSize(1001, 468);
     
//        jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel11 = new javax.swing.JLabel();
                jPanel8 = new javax.swing.JPanel();
                jLabel73 = new javax.swing.JLabel();
                jLabel74 = new javax.swing.JLabel();
                jLabel75 = new javax.swing.JLabel();
                jLabel76 = new javax.swing.JLabel();
                jLabel77 = new javax.swing.JLabel();
                jLabel78 = new javax.swing.JLabel();
                jLabel79 = new javax.swing.JLabel();
                jLabel80 = new javax.swing.JLabel();
                jLabel81 = new javax.swing.JLabel();
                jLabel82 = new javax.swing.JLabel();
                lblUpperDashboard71 = new javax.swing.JLabel();
                lblUpperDashboard72 = new javax.swing.JLabel();
                lblUpperDashboard73 = new javax.swing.JLabel();
                lblUpperDashboard74 = new javax.swing.JLabel();
                lblUpperDashboard75 = new javax.swing.JLabel();
                lblUpperDashboard76 = new javax.swing.JLabel();
                lblUpperDashboard77 = new javax.swing.JLabel();
                lblUpperDashboard78 = new javax.swing.JLabel();
                lblUpperDashboard79 = new javax.swing.JLabel();
                lblUpperDashboard80 = new javax.swing.JLabel();
                lblTable9 = new javax.swing.JLabel();
                lblTable10 = new javax.swing.JLabel();
                lblTable5 = new javax.swing.JLabel();
                lblTable1 = new javax.swing.JLabel();
                lblTable6 = new javax.swing.JLabel();
                lblTable3 = new javax.swing.JLabel();
                lblTable4 = new javax.swing.JLabel();
                lblTable7 = new javax.swing.JLabel();
                lblTable8 = new javax.swing.JLabel();
                lblTable2 = new javax.swing.JLabel();

                jLabel11.setText("jLabel11");

                jPanel8.setBackground(new java.awt.Color(255, 255, 255));
                jPanel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

                jLabel73.setOpaque(true);

                lblUpperDashboard71.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                lblUpperDashboard71.setText("Table 1");

                lblUpperDashboard72.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                lblUpperDashboard72.setText("Table 3");

                lblUpperDashboard73.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                lblUpperDashboard73.setText("Table 2");

                lblUpperDashboard74.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                lblUpperDashboard74.setText("Table 4");

                lblUpperDashboard75.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                lblUpperDashboard75.setText("Table 5");

                lblUpperDashboard76.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                lblUpperDashboard76.setText("Table 6");

                lblUpperDashboard77.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                lblUpperDashboard77.setText("Table 8");

                lblUpperDashboard78.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                lblUpperDashboard78.setText("Table 7");

                lblUpperDashboard79.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                lblUpperDashboard79.setText("Table 9");

                lblUpperDashboard80.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                lblUpperDashboard80.setText("Table 10");

                lblTable9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                lblTable9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinner-table (1).png"))); // NOI18N
                lblTable9.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblTable9lblTable9MouseClicked(evt);
                        }
                });

                lblTable10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                lblTable10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinner-table (1).png"))); // NOI18N
                lblTable10.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblTable10lblTable10MouseClicked(evt);
                        }
                });

                lblTable5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                lblTable5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinner-table (1).png"))); // NOI18N
                lblTable5.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblTable5MouseClicked(evt);
                        }
                });

                lblTable1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                lblTable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinner-table (1).png"))); // NOI18N
                lblTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblTable1lblTable1MouseClicked(evt);
                        }
                });

                lblTable6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                lblTable6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinner-table (1).png"))); // NOI18N
                lblTable6.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblTable6lblTable6MouseClicked(evt);
                        }
                });

                lblTable3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                lblTable3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinner-table (1).png"))); // NOI18N
                lblTable3.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblTable3lblTable3MouseClicked(evt);
                        }
                });

                lblTable4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                lblTable4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinner-table (1).png"))); // NOI18N
                lblTable4.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblTable4lblTable4MouseClicked(evt);
                        }
                });

                lblTable7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                lblTable7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinner-table (1).png"))); // NOI18N
                lblTable7.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblTable7MouseClicked(evt);
                        }
                });

                lblTable8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                lblTable8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinner-table (1).png"))); // NOI18N
                lblTable8.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblTable8lblTable8MouseClicked(evt);
                        }
                });

                lblTable2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                lblTable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dinner-table (1).png"))); // NOI18N
                lblTable2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblTable2lblTable2MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
                jPanel8.setLayout(jPanel8Layout);
                jPanel8Layout.setHorizontalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addComponent(lblUpperDashboard76, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(128, 128, 128)
                                                .addComponent(lblUpperDashboard78, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(129, 129, 129)
                                                .addComponent(lblUpperDashboard77, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(113, 113, 113)
                                                .addComponent(lblUpperDashboard79, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(lblUpperDashboard71, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(124, 124, 124)
                                                .addComponent(lblUpperDashboard73, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(108, 108, 108)
                                                .addComponent(lblUpperDashboard72, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblUpperDashboard74, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(101, 101, 101)))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(lblUpperDashboard80, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(71, 71, 71))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                .addComponent(lblUpperDashboard75, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(51, 51, 51))))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(lblTable6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53)
                                                .addComponent(lblTable7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(jLabel77)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel74)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                                .addComponent(jLabel82)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblTable2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(47, 47, 47)))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(jLabel79)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblTable3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                                .addComponent(jLabel78)
                                                                .addGap(70, 70, 70)
                                                                .addComponent(jLabel80))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                                .addComponent(jLabel73)
                                                                .addGap(70, 70, 70)
                                                                .addComponent(jLabel75)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblTable4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(lblTable8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(59, 59, 59)
                                                .addComponent(lblTable9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel81))
                                                        .addComponent(jLabel76, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblTable5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(lblTable10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(29, Short.MAX_VALUE))
                );
                jPanel8Layout.setVerticalGroup(
                        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel76)
                                                        .addComponent(jLabel73)
                                                        .addComponent(jLabel74)
                                                        .addComponent(jLabel77)
                                                        .addComponent(jLabel75))
                                                .addGap(70, 70, 70)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel81)
                                                        .addComponent(jLabel78)
                                                        .addComponent(jLabel79)
                                                        .addComponent(jLabel82)
                                                        .addComponent(jLabel80))
                                                .addGap(43, 43, 43))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblTable4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblTable5, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblTable3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblTable1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblTable2, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblUpperDashboard72, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblUpperDashboard73, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblUpperDashboard71, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblUpperDashboard74, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblUpperDashboard75, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblTable6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblTable7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblTable8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblTable9, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(lblTable10)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblUpperDashboard77, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblUpperDashboard78, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblUpperDashboard79, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblUpperDashboard80, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblUpperDashboard76, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
        }// </editor-fold>//GEN-END:initComponents

    private void lblTable9lblTable9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTable9lblTable9MouseClicked
            openOrderDetails("Table 9");
    }//GEN-LAST:event_lblTable9lblTable9MouseClicked

    private void lblTable10lblTable10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTable10lblTable10MouseClicked
            openOrderDetails("Table 10");
    }//GEN-LAST:event_lblTable10lblTable10MouseClicked

    private void lblTable1lblTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTable1lblTable1MouseClicked
        openOrderDetails("Table 1");
    }//GEN-LAST:event_lblTable1lblTable1MouseClicked

    private void lblTable6lblTable6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTable6lblTable6MouseClicked
        openOrderDetails("Table 6");
    }//GEN-LAST:event_lblTable6lblTable6MouseClicked

    private void lblTable3lblTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTable3lblTable3MouseClicked
            openOrderDetails("Table 3");
    }//GEN-LAST:event_lblTable3lblTable3MouseClicked

    private void lblTable4lblTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTable4lblTable4MouseClicked
        openOrderDetails("Table 4");
    }//GEN-LAST:event_lblTable4lblTable4MouseClicked

    private void lblTable8lblTable8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTable8lblTable8MouseClicked
       openOrderDetails("Table 8");
    }//GEN-LAST:event_lblTable8lblTable8MouseClicked

    private void lblTable2lblTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTable2lblTable2MouseClicked
       openOrderDetails("Table 2");
    }//GEN-LAST:event_lblTable2lblTable2MouseClicked

    private void lblTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTable5MouseClicked
        openOrderDetails("Table 5");
    }//GEN-LAST:event_lblTable5MouseClicked

    private void lblTable7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTable7MouseClicked
             openOrderDetails("Table 7");
    }//GEN-LAST:event_lblTable7MouseClicked
       
        /**
                * The below method will  add the another panel to the frame & this add order panel will setVisible as false
                * & add the addDetails panel will table table number
                *
                * @param:tableNo 
                * @return:void
                *
         */
        private void openOrderDetails(String tableNo ){
//        jTabbedPane1.setSelectedIndex(1);
            orderDetails.getTableNo().setText(tableNo);
            dashboard.getPnlDisplay().add(orderDetails);
            orderDetails.setVisible(true);
            this.setVisible(false);            
    }
     
    
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel73;
        private javax.swing.JLabel jLabel74;
        private javax.swing.JLabel jLabel75;
        private javax.swing.JLabel jLabel76;
        private javax.swing.JLabel jLabel77;
        private javax.swing.JLabel jLabel78;
        private javax.swing.JLabel jLabel79;
        private javax.swing.JLabel jLabel80;
        private javax.swing.JLabel jLabel81;
        private javax.swing.JLabel jLabel82;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JLabel lblTable1;
        private javax.swing.JLabel lblTable10;
        private javax.swing.JLabel lblTable2;
        private javax.swing.JLabel lblTable3;
        private javax.swing.JLabel lblTable4;
        private javax.swing.JLabel lblTable5;
        private javax.swing.JLabel lblTable6;
        private javax.swing.JLabel lblTable7;
        private javax.swing.JLabel lblTable8;
        private javax.swing.JLabel lblTable9;
        private javax.swing.JLabel lblUpperDashboard71;
        private javax.swing.JLabel lblUpperDashboard72;
        private javax.swing.JLabel lblUpperDashboard73;
        private javax.swing.JLabel lblUpperDashboard74;
        private javax.swing.JLabel lblUpperDashboard75;
        private javax.swing.JLabel lblUpperDashboard76;
        private javax.swing.JLabel lblUpperDashboard77;
        private javax.swing.JLabel lblUpperDashboard78;
        private javax.swing.JLabel lblUpperDashboard79;
        private javax.swing.JLabel lblUpperDashboard80;
        // End of variables declaration//GEN-END:variables
    private Vector items = new Vector();
}
