package UIDesign;

import Database.CategoryDatabase;
import Database.CustomJTable;
import Database.ItemsDatabase;
import java.awt.Color;
import java.awt.Font;
import jiconfont.icons.FontAwesome;
import jiconfont.swing.IconFontSwing;
import Database.OrderDatabase;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import networking.*;

/**
 *
 * @author Tarun
 */
public class Dashboard extends javax.swing.JFrame {

        public ItemsDatabase itemsDatabase = null;
        CategoryDatabase categoryDatabase = null;
        public OrderDatabase orderDatabase = null;
        public CustomJTable customJTable = null;
        Notification notification = null;
        OrderDetails orderDetails = null;
        Server server = null;
        public ObjectInputStream in = null;
        public ObjectOutputStream out = null;
          /**
         * ************************CONSTRUCTOR*****************************
         * This initialized the connection object & make connection to db
         */
        /**
         * Creates new form Dashboard
         */
        public Dashboard() {
                initComponents();
                itemsDatabase = new ItemsDatabase();
                categoryDatabase = new CategoryDatabase();
                customJTable = new CustomJTable();
                notification = new Notification(customJTable);
                orderDatabase = new OrderDatabase(this);
                createDatabase = new CreateDatabase(categoryDatabase, itemsDatabase, this);
                server = new Server(notification, this);

                orderDetails = new OrderDetails(itemsDatabase, categoryDatabase, notification, server, orderDatabase);

                addOrder = new AddOrder(orderDetails, this);
                dashboardPanel = new DashboardPanel(this);

                lblDashboard.setFont(new Font("Segoe UI", Font.BOLD + Font.ITALIC, 20));
                pnlDisplay.add(dashboardPanel);
                dashboardPanel.setVisible(true);

                IconFontSwing.register(FontAwesome.getIconFont());
                lblLogout.setIcon(IconFontSwing.buildIcon(FontAwesome.SIGN_OUT, 30, new Color(182, 44, 209)));
                lblDashboard.setIcon(IconFontSwing.buildIcon(FontAwesome.TACHOMETER, 35, new Color(182, 44, 209)));
                lblAddOrders.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_SQUARE_O, 30, new Color(182, 44, 209)));
                lblNotification.setIcon(IconFontSwing.buildIcon(FontAwesome.BELL, 30, new Color(182, 44, 209)));
                lblCreateDb.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_CIRCLE, 30, new Color(182, 44, 209)));
                
                server.start();
        }
         /**
                * The below method will initialize the ObjectOutputStream & ObjectInputStream of the Server
                * always initialize the ObjectOutputStream first Then ObjectInputStream
                *
                * @param:Nothing 
                * @return:Nothing 
                *
         */
        public void initStream() {
                try {
                        if (server.getClientSocket() != null) {
                                out = new ObjectOutputStream(server.getClientSocket().getOutputStream());
                                in = new ObjectInputStream(server.getClientSocket().getInputStream());
                        }
                } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "Exception : " + ex, "dashboard", JOptionPane.ERROR_MESSAGE);
                }
        }

        /**
         * *************************GETTER************************
         */
        public AddOrder getAddOrder() {
                return addOrder;
        }

        public JPanel getPnlDisplay() {
                return pnlDisplay;
        }

        public OrderDetails getOrderDetails() {
                return orderDetails;
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        pnlLeftside = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlDashboard = new javax.swing.JPanel();
        lblDashboard = new javax.swing.JLabel();
        pnlAddOrders = new javax.swing.JPanel();
        lblAddOrders = new javax.swing.JLabel();
        pnlNotification = new javax.swing.JPanel();
        lblNotification = new javax.swing.JLabel();
        pnlLogout = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        pnlCreateDb = new javax.swing.JPanel();
        lblCreateDb = new javax.swing.JLabel();
        pnlDisplay = new javax.swing.JPanel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlLeftside.setBackground(new java.awt.Color(36, 11, 54));
        pnlLeftside.setForeground(new java.awt.Color(182, 44, 209));

        lblImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\picture\\restaurants.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Restaurant Manager");

        pnlDashboard.setBackground(new java.awt.Color(255, 255, 255));

        lblDashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(182, 44, 209));
        lblDashboard.setText("Dashboard");
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlAddOrders.setBackground(new java.awt.Color(36, 11, 54));

        lblAddOrders.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAddOrders.setForeground(new java.awt.Color(182, 44, 209));
        lblAddOrders.setText("Add Orders");
        lblAddOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddOrdersMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAddOrdersLayout = new javax.swing.GroupLayout(pnlAddOrders);
        pnlAddOrders.setLayout(pnlAddOrdersLayout);
        pnlAddOrdersLayout.setHorizontalGroup(
            pnlAddOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAddOrdersLayout.setVerticalGroup(
            pnlAddOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddOrdersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAddOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlNotification.setBackground(new java.awt.Color(36, 11, 54));

        lblNotification.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNotification.setForeground(new java.awt.Color(182, 44, 209));
        lblNotification.setText("Notification");
        lblNotification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotificationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlNotificationLayout = new javax.swing.GroupLayout(pnlNotification);
        pnlNotification.setLayout(pnlNotificationLayout);
        pnlNotificationLayout.setHorizontalGroup(
            pnlNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlNotificationLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblNotification, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlNotificationLayout.setVerticalGroup(
            pnlNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
            .addGroup(pnlNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblNotification, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
        );

        pnlLogout.setBackground(new java.awt.Color(36, 11, 54));

        lblLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(182, 44, 209));
        lblLogout.setText("Logout");

        javax.swing.GroupLayout pnlLogoutLayout = new javax.swing.GroupLayout(pnlLogout);
        pnlLogout.setLayout(pnlLogoutLayout);
        pnlLogoutLayout.setHorizontalGroup(
            pnlLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlLogoutLayout.setVerticalGroup(
            pnlLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        pnlCreateDb.setBackground(new java.awt.Color(36, 11, 54));

        lblCreateDb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCreateDb.setForeground(new java.awt.Color(182, 44, 209));
        lblCreateDb.setText("Create Database");
        lblCreateDb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCreateDbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlCreateDbLayout = new javax.swing.GroupLayout(pnlCreateDb);
        pnlCreateDb.setLayout(pnlCreateDbLayout);
        pnlCreateDbLayout.setHorizontalGroup(
            pnlCreateDbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlCreateDbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCreateDbLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblCreateDb, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlCreateDbLayout.setVerticalGroup(
            pnlCreateDbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
            .addGroup(pnlCreateDbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblCreateDb, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlLeftsideLayout = new javax.swing.GroupLayout(pnlLeftside);
        pnlLeftside.setLayout(pnlLeftsideLayout);
        pnlLeftsideLayout.setHorizontalGroup(
            pnlLeftsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddOrders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlNotification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCreateDb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftsideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
            .addComponent(pnlDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlLeftsideLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblImage)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlLeftsideLayout.setVerticalGroup(
            pnlLeftsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftsideLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pnlDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pnlAddOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pnlCreateDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlNotification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(pnlLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pnlDisplay.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlDisplayLayout = new javax.swing.GroupLayout(pnlDisplay);
        pnlDisplay.setLayout(pnlDisplayLayout);
        pnlDisplayLayout.setHorizontalGroup(
            pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
        );
        pnlDisplayLayout.setVerticalGroup(
            pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLeftside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLeftside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAddOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddOrdersMouseClicked
//        pnlDisplay.add(addOrders);
//        addOrders.setVisible(true);
//        dashboardPanel.setVisible(false);

            pnlDisplay.add(addOrder);
            makeThisVisiable(addOrder);

            pnlDashboard.setBackground(new Color(36, 11, 54));
            pnlAddOrders.setBackground(new Color(255, 255, 255));
            pnlCreateDb.setBackground(new Color(36, 11, 54));
            pnlLogout.setBackground(new Color(36, 11, 54));
            pnlNotification.setBackground(new Color(36, 11, 54));

            Font f = new Font("Segoe UI", Font.BOLD + Font.ITALIC, 20);
            lblAddOrders.setFont(f);
            f = new Font("Segoe UI", Font.PLAIN, 18);
            lblDashboard.setFont(f);
            lblCreateDb.setFont(f);
            lblNotification.setFont(f);
            lblLogout.setFont(f);

            lblLogout.setIcon(IconFontSwing.buildIcon(FontAwesome.SIGN_OUT, 30, new Color(182, 44, 209)));
            lblDashboard.setIcon(IconFontSwing.buildIcon(FontAwesome.TACHOMETER, 30, new Color(182, 44, 209)));
            lblAddOrders.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_SQUARE_O, 35, new Color(182, 44, 209)));
            lblNotification.setIcon(IconFontSwing.buildIcon(FontAwesome.BELL, 30, new Color(182, 44, 209)));
            lblCreateDb.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_CIRCLE, 30, new Color(182, 44, 209)));

    }//GEN-LAST:event_lblAddOrdersMouseClicked

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
            makeThisVisiable(dashboardPanel);

            pnlDashboard.setBackground(new Color(255, 255, 255));
            pnlAddOrders.setBackground(new Color(36, 11, 54));
            pnlCreateDb.setBackground(new Color(36, 11, 54));
            pnlLogout.setBackground(new Color(36, 11, 54));
            pnlNotification.setBackground(new Color(36, 11, 54));

            Font f = new Font("Segoe UI", Font.BOLD + Font.ITALIC, 20);
            lblDashboard.setFont(f);
            f = new Font("Segoe UI", Font.PLAIN, 18);
            lblAddOrders.setFont(f);
            lblCreateDb.setFont(f);
            lblNotification.setFont(f);
            lblLogout.setFont(f);

            lblLogout.setIcon(IconFontSwing.buildIcon(FontAwesome.SIGN_OUT, 30, new Color(182, 44, 209)));
            lblDashboard.setIcon(IconFontSwing.buildIcon(FontAwesome.TACHOMETER, 35, new Color(182, 44, 209)));
            lblAddOrders.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_SQUARE_O, 30, new Color(182, 44, 209)));
            lblNotification.setIcon(IconFontSwing.buildIcon(FontAwesome.BELL, 30, new Color(182, 44, 209)));
            lblCreateDb.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_CIRCLE, 30, new Color(182, 44, 209)));

    }//GEN-LAST:event_lblDashboardMouseClicked

    private void lblCreateDbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCreateDbMouseClicked
            pnlDisplay.add(createDatabase);
            makeThisVisiable(createDatabase);

            pnlDashboard.setBackground(new Color(36, 11, 54));
            pnlAddOrders.setBackground(new Color(36, 11, 54));
            pnlCreateDb.setBackground(new Color(255, 255, 255));
            pnlLogout.setBackground(new Color(36, 11, 54));
            pnlNotification.setBackground(new Color(36, 11, 54));

            Font f = new Font("Segoe UI", Font.BOLD + Font.ITALIC, 20);
            lblCreateDb.setFont(f);
            f = new Font("Segoe UI", Font.PLAIN, 18);
            lblAddOrders.setFont(f);
            lblDashboard.setFont(f);
            lblNotification.setFont(f);
            lblLogout.setFont(f);

            lblLogout.setIcon(IconFontSwing.buildIcon(FontAwesome.SIGN_OUT, 30, new Color(182, 44, 209)));
            lblDashboard.setIcon(IconFontSwing.buildIcon(FontAwesome.TACHOMETER, 30, new Color(182, 44, 209)));
            lblAddOrders.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_SQUARE_O, 30, new Color(182, 44, 209)));
            lblNotification.setIcon(IconFontSwing.buildIcon(FontAwesome.BELL, 30, new Color(182, 44, 209)));
            lblCreateDb.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_CIRCLE, 35, new Color(182, 44, 209)));
    }//GEN-LAST:event_lblCreateDbMouseClicked

    private void lblNotificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotificationMouseClicked
            pnlDisplay.add(notification);
            makeThisVisiable(notification);

            pnlDashboard.setBackground(new Color(36, 11, 54));
            pnlAddOrders.setBackground(new Color(36, 11, 54));
            pnlCreateDb.setBackground(new Color(36, 11, 54));
            pnlLogout.setBackground(new Color(36, 11, 54));
            pnlNotification.setBackground(new Color(255, 255, 255));

            Font f = new Font("Segoe UI", Font.BOLD + Font.ITALIC, 20);
            lblNotification.setFont(f);
            f = new Font("Segoe UI", Font.PLAIN, 18);
            lblAddOrders.setFont(f);
            lblDashboard.setFont(f);
            lblCreateDb.setFont(f);
            lblLogout.setFont(f);

            lblLogout.setIcon(IconFontSwing.buildIcon(FontAwesome.SIGN_OUT, 30, new Color(182, 44, 209)));
            lblDashboard.setIcon(IconFontSwing.buildIcon(FontAwesome.TACHOMETER, 30, new Color(182, 44, 209)));
            lblAddOrders.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_SQUARE_O, 30, new Color(182, 44, 209)));
            lblNotification.setIcon(IconFontSwing.buildIcon(FontAwesome.BELL, 35, new Color(182, 44, 209)));
            lblCreateDb.setIcon(IconFontSwing.buildIcon(FontAwesome.PLUS_CIRCLE, 30, new Color(182, 44, 209)));
    }//GEN-LAST:event_lblNotificationMouseClicked
        /**
         * The below method make the panel is visible when the navigation which
         * is left side in our application is clicked
         *
         * @param:Panel
         * @return:Nothing
         *
         */
        public void makeThisVisiable(JPanel jp) {
                createDatabase.setVisible(false);
                dashboardPanel.setVisible(false);
                addOrder.setVisible(false);
                notification.setVisible(false);
                orderDetails.setVisible(false);
                jp.setVisible(true);
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
                                        break;
                                }
                        }//info.getClassName()
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Dashboard().setVisible(true);
                        }
                });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAddOrders;
    private javax.swing.JLabel lblCreateDb;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblNotification;
    private javax.swing.JPanel pnlAddOrders;
    private javax.swing.JPanel pnlCreateDb;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlDisplay;
    private javax.swing.JPanel pnlLeftside;
    private javax.swing.JPanel pnlLogout;
    private javax.swing.JPanel pnlNotification;
    // End of variables declaration//GEN-END:variables
    private AddOrder addOrder;
        public DashboardPanel dashboardPanel;
        private CreateDatabase createDatabase;
}
